//
// Created by niluogege on 2023/2/10.
//

#ifndef NDKDEMO_COM_NILUOGEGE_NDKDEMO_GIFLIB_GIFMANAGER_H
#define NDKDEMO_COM_NILUOGEGE_NDKDEMO_GIFLIB_GIFMANAGER_H


class com_niluogege_ndkdemo_giflib_GifManager {

};


#endif //NDKDEMO_COM_NILUOGEGE_NDKDEMO_GIFLIB_GIFMANAGER_H
